apiVersion: v2
name: udintsev-hw
description: OTUS architect course, homework

type: application

version: 0.1.2
appVersion: "latest"

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - hw-database
  - name: keycloak
    version: 0.1.x
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
    tags:
      - hw-idp
