replicaCount: 2

image:
  repository: udintsev/hw

service:
  type: ClusterIP
  port: 8080

ingress:
  proto: http
  host: arch.labs
  pathPrefix: /otusapp/audintsev
  appPath: /app
  authPath: /auth

keycloakUser: admin
keycloakPassword: admin
keycloakRealm: myrealm
keycloakClient: myclient

metrics:
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  nameOverride: db-app
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      interval: 15s

keycloak:
  enabled: true
  postgresql:
    nameOverride: db-keycloak
  service:
    type: ClusterIP
  extraEnvFrom: |
    - configMapRef:
        name: udintsev-hw-keycloak
    - secretRef:
        name: udintsev-hw-keycloak
