replicaCount: 2

image:
  repository: udintsev/hw

service:
  type: ClusterIP
  port: 8080

ingress:
  host: arch.homework
  pathPrefix: /otusapp/audintsev

metrics:
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      interval: 15s
