replicaCount: 2

image:
  repository: udintsev/hw

service:
  type: ClusterIP
  port: 8080

ingress:
  host: arch.homework
  pathPrefix: /otusapp/audintsev

metrics:
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  nameOverride: app-db
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      interval: 15s

keycloak:
  enabled: true
  postgresql:
    nameOverride: keycloak-db
  auth:
    createAdminUser: true
    adminUser: admin
    adminPassword: admin
  service:
    type: ClusterIP
  args:
    - "/opt/bitnami/scripts/keycloak/run.sh"
    - "-Dkeycloak.frontendUrl=http://arch.homework/otusapp/audintsev/auth"
