{
 "title": "MyApp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX 5xx rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{path=\"/otusapp/audintsev($|/)(.*)\", status =~ \"5..\"}[1m])",
     "legendFormat": "5xx rate"
    }
   ]
  },
  {
   "title": "NGINX RPS by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_request_duration_seconds_count{path=\"/otusapp/audintsev($|/)(.*)\"}[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "NGINX Latency GET, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/otusapp/audintsev($|/)(.*)\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "50th pctl"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/otusapp/audintsev($|/)(.*)\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "95th pctl"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/otusapp/audintsev($|/)(.*)\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "99th pctl"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/otusapp/audintsev($|/)(.*)\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "APP 5xx rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_count{service =~\".*homework.*\", uri !~ \"/actuator.*\", status =~ \"5..\" }[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "APP RPS by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_count{service =~\".*homework.*\", uri !~ \"/actuator.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "APP Latency GET, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{service =~\".*homework.*\", uri !~ \"/actuator.*\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "50th pctl {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{service =~\".*homework.*\", uri !~ \"/actuator.*\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "95th pctl {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{service =~\".*homework.*\", uri !~ \"/actuator.*\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "99th pctl {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{service =~\".*homework.*\", uri !~ \"/actuator.*\", method=\"GET\"}[1m]))) * 1000",
     "legendFormat": "max {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "RAM utilization, MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image =~ \"udintsev.*\"} / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU utilization, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image =~ \"udintsev/.*\"}[1m]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(r2dbc_pool_pending_connections)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(r2dbc_pool_allocated_connections)",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(r2dbc_pool_acquired_connections)",
     "legendFormat": "Acquired"
    }
   ]
  }
 ]
}