apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}
  namespace: {{ .Release.Namespace }}
data:
  spring.r2dbc.url: {{ printf "r2dbc:postgresql://%s:%s/%s" (include "udintsev-hw-chart.dbFullname" .) .Values.postgresql.service.port  .Values.postgresql.postgresqlDatabase }}
  spring.r2dbc.username: {{ .Values.postgresql.postgresqlUsername }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  spring.r2dbc.password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
