apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udintsev-hw-chart.name" . }}-app
  namespace: {{ .Release.Namespace }}
data:
  spring.r2dbc.url: {{ printf "r2dbc:postgresql://%s:%s/%s" (include "udintsev-hw-chart.dbFullname" .) .Values.postgresql.service.port  .Values.postgresql.postgresqlDatabase }}
  spring.r2dbc.username: {{ .Values.postgresql.postgresqlUsername }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udintsev-hw-chart.name" . }}-app
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  spring.r2dbc.password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udintsev-hw-chart.name" . }}-keycloak
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_FRONTEND_URL: "{{ (include "udintsev-hw-chart.keycloakFrontendUrl" .) }}"
  KEYCLOAK_INTERNAL_URL: "http://{{ include "udintsev-hw-chart.keycloakFullname" . }}-http/auth"
  PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_USER: "{{ .Values.keycloakUser }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udintsev-hw-chart.name" . }}-keycloak
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  KEYCLOAK_PASSWORD: {{ .Values.keycloakPassword | b64enc | quote }}
