apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework6-chart.fullname" . }}
  labels:
    {{- include "homework6-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "homework6-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homework6-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ printf "%s-app" (include "homework6-chart.fullname" .) }}"
            - secretRef:
                name: "{{ printf "%s-app" (include "homework6-chart.fullname" .) }}"
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
