apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udintsev-hw-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "udintsev-hw-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "udintsev-hw-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "udintsev-hw-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}"
            - secretRef:
                name: "{{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}"
          env:
            - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
              value: "{{ print "%s%s/auth" .Values.ingress.host .Values.ingress.pathPrefix }}"
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
