apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udintsev-hw-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "udintsev-hw-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "udintsev-hw-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "udintsev-hw-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: wait-jwt-issuer-ready
          image: busybox
          env:
            - name: JWT_ISSUER_URL
              value: "{{ (include "udintsev-hw-chart.jwtIssuerUrl" .) }}"
          command:
            - sh
            - "-c"
            - |
              until wget --spider $JWT_ISSUER_URL;
              do sleep 1; done
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}"
            - secretRef:
                name: "{{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}"
          env:
            - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
              value: "{{ (include "udintsev-hw-chart.jwtIssuerUrl" .) }}"
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
