apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "udintsev-hw-chart.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /auth/$2
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ .Values.ingress.pathPrefix }}{{ .Values.ingress.authPath }}($|/)(.*)
            backend:
              serviceName: {{ include "udintsev-hw-chart.keycloakFullname" . }}-http
              servicePort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "udintsev-hw-chart.fullname" . }}-gw
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ include "udintsev-hw-chart.gwIngressPath" . }}
            backend:
              serviceName: {{ include "udintsev-hw-chart.fullname" . }}-gw
              servicePort: http
