apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-auth" (include "udintsev-hw-chart.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /auth/$2
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ printf "%s%s($|/)(.*)" .Values.ingress.pathPrefix .Values.ingress.authPath }}
            backend:
              serviceName: {{ include "udintsev-hw-chart.keycloakFullname" . }}-http
              servicePort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-app" (include "udintsev-hw-chart.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ printf "%s%s($|/)(.*)" .Values.ingress.pathPrefix .Values.ingress.appPath }}
            backend:
              serviceName: {{ include "udintsev-hw-chart.fullname" . }}
              servicePort: http
