apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "udintsev-hw-chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ printf "%s($|/)(.*)" .Values.ingress.pathPrefix }}
            backend:
              serviceName: {{ include "udintsev-hw-chart.fullname" . }}
              servicePort: http
