apiVersion: v1
kind: ConfigMap
metadata:
  name: homework6-configmap
data:
  POSTGRES_HOST: postgres-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_USER: myuser
  POSTGRES_DB: myapp
  APP_DB_URI: r2dbc:postgresql://postgres-postgresql/myapp
---
apiVersion: v1
kind: Secret
metadata:
  name: homework6-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dk
